version: '3.9'

volumes:
  dbdata:

services:
  db:
    image: mysql
    ports:
      - '9001:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=blog
      - MYSQL_DATABASE=blog
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '9002:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=blog
      - PMA_PASSWORD=pass
    depends_on:
      - db

  web:
    image: nginx:1.19.4-alpine
    ports:
      - '9003:80'
    depends_on:
      - app
    volumes:
      - ./deployment/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public

  app:
    build:
      context: .
      dockerfile: deployment/local/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ./:/var/www
      - ~/.composer-docker/cache:/root/.composer/cache
